name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run prod
        env:
          BITBUCKET_CLIENT_ID: ${{ secrets.BITBUCKET_CLIENT_ID }}
          FIXED_WORKSPACE_ID: ${{ secrets.FIXED_WORKSPACE_ID }}
      - name: Adopt to gh-pages
        run: |
          sed -i 's/\"\//\"\/jg-docs\//' www/ngsw.json
          sed -i 's/base href=\"\//base href=\"\/jg-docs\//' www/index.html
          cp www/index.html www/404.html
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: www
